---
name: main

on:
  push:
    branches:
      - '**'

jobs:
  test:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'
      - name: Cache npm packages
        uses: actions/cache@v2
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-
            ${{ runner.os }}-
      - name: Install dependencies
        run: npm ci
      - name: Download Benthos
        run: |
          benthos_version="$(jq -r .blobpack.version < package.json)"
          benthos_src="$(jq -r .blobpack.src < package.json)/v${benthos_version}"
          benthos_archive="benthos_${benthos_version}_linux_amd64.tar.gz"
          curl -fsSL --create-dirs -o "tmp/${benthos_archive}" \
            "${benthos_src}/${benthos_archive}"
          curl -fsSL -o tmp/benthos_checksums.txt \
            "${benthos_src}/benthos_${benthos_version}_checksums.txt"
          cd tmp
          sha256sum --strict --ignore-missing --check benthos_checksums.txt
          mv "${benthos_archive}" benthos.tar.gz
      - name: Install Benthos to PATH
        run: |
          cd tmp
          tar -xzf benthos.tar.gz
          mkdir -p bin
          mv benthos bin
          echo "$(pwd)/bin" >> $GITHUB_PATH
      - name: Build
        run: npm run build
      - name: Test
        run: npm test
  lint:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'
      - name: Cache npm packages
        uses: actions/cache@v2
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-
            ${{ runner.os }}-
      - name: Install dependencies
        run: npm ci
      - name: Lint
        run: npm run lint
  package:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'
      - name: Cache npm packages
        uses: actions/cache@v2
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-
            ${{ runner.os }}-
      - name: Install dependencies
        run: npm ci
      - name: Build
        run: npm run build
      - name: Serverless package
        run: npm run sls:package
